--  Tables Tables Tables Tables Tables Tables Tables Tables --



--  Table COMPAGNIE_ASSURENCE


CREATE TABLE "COMPAGNIE_ASSURENCE" 
(	"CODE_COMPAGNIE_ASSURENCE" NUMBER(11,0), 
	"NOM_COMPAGNIE_ASSURENCE" VARCHAR2(255), 
	"NUMERO_TEL_COMPAGNIE_ASSURENCE" VARCHAR2(255), 
	"ADRESSE_COMPAGNIE_ASSURENCE" VARCHAR2(255)
	);
ALTER TABLE "COMPAGNIE_ASSURENCE" ADD CONSTRAINT "COMPAGNIE_ASSURENCE_PK" PRIMARY KEY ("CODE_COMPAGNIE_ASSURENCE");
ALTER TABLE "COMPAGNIE_ASSURENCE" MODIFY ("CODE_COMPAGNIE_ASSURENCE" NOT NULL );


--  Table CONTIENT


CREATE TABLE "CONTIENT" 
(	"CODE_ORDONNANCE" NUMBER(11,0), 
	"CODE_MEDICAMENT" NUMBER(11,0), 
	"QUANTITE_CONTIENT" NUMBER(11,0)
	);
ALTER TABLE "CONTIENT" ADD CONSTRAINT "CONTIENT_PK" PRIMARY KEY ("CODE_ORDONNANCE", "CODE_MEDICAMENT");
ALTER TABLE "CONTIENT" MODIFY ("CODE_ORDONNANCE" NOT NULL );
ALTER TABLE "CONTIENT" MODIFY ("CODE_MEDICAMENT" NOT NULL );
ALTER TABLE "CONTIENT" ADD CONSTRAINT "CONTIENT_MEDICAMENT_FK1" FOREIGN KEY ("CODE_MEDICAMENT")
	REFERENCES "MEDICAMENT" ("CODE_MEDICAMENT") ;
ALTER TABLE "CONTIENT" ADD CONSTRAINT "CONTIENT_ORDONNANCE_FK1" FOREIGN KEY ("CODE_ORDONNANCE")
	REFERENCES "ORDONNANCE" ("CODE_ORDONNANCE") ;


--  Table DIAGNOSTIC


CREATE TABLE "DIAGNOSTIC" 
(	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"TEMPERATURE_DIAGNOSTIC" NUMBER(11,0), 
	"TENSION_ATERIELLE_DIAGNOSTIC" NUMBER(11,0), 
	"POIDS_DIAGNOSTIC" NUMBER(11,0), 
	"MESURE_DIAGNOSTIC" NUMBER(11,0), 
	"RYTHME_CARDIAQUE_DIAGNOSTIC" VARCHAR2(255), 
	"AUTR_REMARQUE_DIAGNOSTIC" VARCHAR2(512), 
	"SYSTEM_RESPIRATOIR_DIAGNOSTIC" VARCHAR2(250), 
	"ABDOMEN_DIAGNOSTIC" VARCHAR2(250), 
	"MEMBRES_SUP_DIAGNOSTIC" VARCHAR2(250), 
	"MEMBRES_INF_DIAGNOSTIC" VARCHAR2(250), 
	"ORGAN_GENITAUX_DIAGNOSTIC" VARCHAR2(250), 
	"PEAU_DIAGNOSTIC" VARCHAR2(250), 
	"TETE_COU_DIAGNOSTIC" VARCHAR2(250), 
	"CODE_EXAMEN_SANG" NUMBER(11,0), 
	"CODE_EXAMEN_URINE" NUMBER(11,0)
	);
ALTER TABLE "DIAGNOSTIC" ADD CONSTRAINT "DIAGNOSTIC_PK" PRIMARY KEY ("CODE_DIAGNOSTIC");
ALTER TABLE "DIAGNOSTIC" MODIFY ("CODE_DIAGNOSTIC" NOT NULL );
ALTER TABLE "DIAGNOSTIC" ADD CONSTRAINT "DIAGNOSTIC_EXAMEN_SANG_FK1" FOREIGN KEY ("CODE_EXAMEN_SANG")
	REFERENCES "EXAMEN_SANG" ("CODE_EXAMEN_SANG") ;
ALTER TABLE "DIAGNOSTIC" ADD CONSTRAINT "DIAGNOSTIC_EXAMEN_URINE_FK1" FOREIGN KEY ("CODE_EXAMEN_URINE")
	REFERENCES "EXAMEN_URINE" ("CODE_EXAMEN_URINE") ;


--  Table ECHOGRAPHIE_TEST


CREATE TABLE "ECHOGRAPHIE_TEST" 
(	"CODE_ECHOGRAPHIE_TEST" NUMBER(11,0), 
	"REMAQUES_ECHOGRAPHIE_TEST" VARCHAR2(512), 
	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"DATE_ECOGRAPHIE_TEST" DATE
	);
ALTER TABLE "ECHOGRAPHIE_TEST" ADD CONSTRAINT "ECHOGRAPHIE_TEST_PK" PRIMARY KEY ("CODE_ECHOGRAPHIE_TEST");
ALTER TABLE "ECHOGRAPHIE_TEST" MODIFY ("CODE_ECHOGRAPHIE_TEST" NOT NULL );
ALTER TABLE "ECHOGRAPHIE_TEST" ADD CONSTRAINT "ECHOGRAPHIE_TEST_DIAGNOST_FK1" FOREIGN KEY ("CODE_DIAGNOSTIC")
	REFERENCES "DIAGNOSTIC" ("CODE_DIAGNOSTIC") ;


--  Table EXAMEN_SANG


CREATE TABLE "EXAMEN_SANG" 
(	"CODE_EXAMEN_SANG" NUMBER(11,0), 
	"HEMATIES_EXAMEN_SANG" NUMBER(11,0), 
	"HEMATOCRITE_EXAMEN_SANG" NUMBER(11,0), 
	"VGM_EXAMEN_SANG" NUMBER(11,0), 
	"TCMH_EXAMEN_SANG" NUMBER(11,0), 
	"CCMH_EXAMEN_SANG" NUMBER(11,0), 
	"LEUCOYTES_EXAMEN_SANG" NUMBER(11,0), 
	"NEUTROPHILES_EXAMEN_SANG" NUMBER(11,0), 
	"EOSINOPHILES_EXAMEN_SANG" NUMBER(11,0), 
	"BASOPHILES_EXAMEN_SANG" NUMBER(11,0), 
	"LYMPHOCYTES_EXAMEN_SANG" NUMBER(11,0), 
	"MONOCYTES_EXAMEN_SANG" NUMBER(11,0), 
	"NUM_PLAQUETTE_EXAMEN_SANG" NUMBER(11,0), 
	"VITESSE_SEDIM_EXAMEN_SANG" NUMBER(11,0), 
	"DATE_EXAMEN_SANG" DATE, 
	"REMARQUES_EXAMEN_SANG" VARCHAR2(512)
	);
ALTER TABLE "EXAMEN_SANG" ADD CONSTRAINT "EXAMEN_SANG_PK" PRIMARY KEY ("CODE_EXAMEN_SANG");
ALTER TABLE "EXAMEN_SANG" MODIFY ("CODE_EXAMEN_SANG" NOT NULL );


--  Table EXAMEN_URINE


CREATE TABLE "EXAMEN_URINE" 
(	"CODE_EXAMEN_URINE" NUMBER(11,0), 
	"GLUCOSE_EXAMEN_URINE" NUMBER(11,0), 
	"BILIRUBINE_EXAMEN_URINE" NUMBER(11,0), 
	"CETONIQUE_EXAMEN_URINE" NUMBER(11,0), 
	"DENSITE_EXAMEN_URINE" NUMBER(11,0), 
	"PH_EXAMEN_URINE" NUMBER(11,0), 
	"PROTEINES_EXAMEN_URINE" NUMBER(11,0), 
	"UROBILINOGENES_EXAMEN_URINE" NUMBER(11,0), 
	"NITRITES" NUMBER(11,0), 
	"LEUCOYTES_EXAMEN_URINE" NUMBER(11,0), 
	"DATE_EXAMEN_URINE" DATE, 
	"REMARQUES_EXAMEN_URINE" VARCHAR2(512)
	);
ALTER TABLE "EXAMEN_URINE" ADD CONSTRAINT "EXAMEN_URINE_PK" PRIMARY KEY ("CODE_EXAMEN_URINE");
ALTER TABLE "EXAMEN_URINE" MODIFY ("CODE_EXAMEN_URINE" NOT NULL );


--  Table FACTURE


CREATE TABLE "FACTURE" 
(	"CODE_FACTURE" NUMBER(11,0), 
	"MONTANT_FACTURE" NUMBER(11,0), 
	"STATUS_FACTURE" VARCHAR2(250), 
	"METHODE_PAYEMENT" VARCHAR2(250)
	);
ALTER TABLE "FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("CODE_FACTURE");
ALTER TABLE "FACTURE" MODIFY ("CODE_FACTURE" NOT NULL );


--  Table IMAGE_ECHOGRAPHIE


CREATE TABLE "IMAGE_ECHOGRAPHIE" 
(	"CODE_IMAGE_ECHOGRAPHIE" NUMBER(11,0), 
	"DESC_IMAGE_ECHOGRAPHIE" VARCHAR2(250), 
	"FILE_IMAGE_ECHOGRAPHIE" VARCHAR2(250), 
	"CODE_ECHOGRAPHIE_TEST" NUMBER(11,0)
	);
ALTER TABLE "IMAGE_ECHOGRAPHIE" ADD CONSTRAINT "IMAGE_ECHOGRAPHIE_PK" PRIMARY KEY ("CODE_IMAGE_ECHOGRAPHIE");
ALTER TABLE "IMAGE_ECHOGRAPHIE" MODIFY ("CODE_IMAGE_ECHOGRAPHIE" NOT NULL );
ALTER TABLE "IMAGE_ECHOGRAPHIE" MODIFY ("FILE_IMAGE_ECHOGRAPHIE" NOT NULL );  
ALTER TABLE "IMAGE_ECHOGRAPHIE" ADD CONSTRAINT "IMAGE_ECHOGRAPHIE_ECHOGRA_FK1" FOREIGN KEY ("CODE_ECHOGRAPHIE_TEST")
	REFERENCES "ECHOGRAPHIE_TEST" ("CODE_ECHOGRAPHIE_TEST") ;


--  Table IMAGE_IRM


CREATE TABLE "IMAGE_IRM" 
(	"CODE_IMAGE_IRM" NUMBER(11,0), 
	"DESC_IMAGE_IRM" VARCHAR2(250), 
	"FILE_IMAGE_IRM" VARCHAR2(250), 
	"CODE_IRM_TEST" NUMBER(11,0)
	);
ALTER TABLE "IMAGE_IRM" ADD CONSTRAINT "IMAGE_IRM_PK" PRIMARY KEY ("CODE_IMAGE_IRM");
ALTER TABLE "IMAGE_IRM" MODIFY ("CODE_IMAGE_IRM" NOT NULL );
ALTER TABLE "IMAGE_IRM" MODIFY ("FILE_IMAGE_IRM" NOT NULL );
ALTER TABLE "IMAGE_IRM" ADD CONSTRAINT "IMAGE_IRM_IRM_TEST_FK1" FOREIGN KEY ("CODE_IRM_TEST")
	REFERENCES "IRM_TEST" ("CODE_IRM_TEST") ;


--  Table IMAGE_RADIOGRAPHIE


CREATE TABLE "IMAGE_RADIOGRAPHIE" 
(	"CODE_IMAGE_RADIOGRAPHIE" NUMBER(11,0), 
	"DESC_IMAGE_RADIOGRAPHIE" VARCHAR2(250), 
	"FILE_IMAGE_RADIOGRAPHIE" VARCHAR2(250), 
	"CODE_RADIOGRAPHIE_TEST" NUMBER(11,0)
	);
ALTER TABLE "IMAGE_RADIOGRAPHIE" ADD CONSTRAINT "IMAGE_RADIOGRAPHIE_PK" PRIMARY KEY ("CODE_IMAGE_RADIOGRAPHIE");
ALTER TABLE "IMAGE_RADIOGRAPHIE" MODIFY ("CODE_IMAGE_RADIOGRAPHIE" NOT NULL );
ALTER TABLE "IMAGE_RADIOGRAPHIE" MODIFY ("FILE_IMAGE_RADIOGRAPHIE" NOT NULL );
ALTER TABLE "IMAGE_RADIOGRAPHIE" ADD CONSTRAINT "IMAGE_RADIOGRAPHIE_RADIOG_FK1" FOREIGN KEY ("CODE_RADIOGRAPHIE_TEST")
	REFERENCES "RADIOGRAPHIE_TEST" ("CODE_RADIOGRAPHIE_TEST") ;


--  Table IMAGE_SCANNER


CREATE TABLE "IMAGE_SCANNER" 
(	"CODE_IMAGE_SCANNER" NUMBER(11,0), 
	"DESC_IMAGE_SCANNER" VARCHAR2(250), 
	"FILE_IMAGE_SCANNER" VARCHAR2(250), 
	"CODE_SCANNER_TEST" NUMBER(11,0)
	);
ALTER TABLE "IMAGE_SCANNER" ADD CONSTRAINT "IMAGE_SCANNER_PK" PRIMARY KEY ("CODE_IMAGE_SCANNER");
ALTER TABLE "IMAGE_SCANNER" MODIFY ("CODE_IMAGE_SCANNER" NOT NULL );
ALTER TABLE "IMAGE_SCANNER" MODIFY ("FILE_IMAGE_SCANNER" NOT NULL );
ALTER TABLE "IMAGE_SCANNER" ADD CONSTRAINT "IMAGE_SCANNER_SCANNER_TES_FK1" FOREIGN KEY ("CODE_SCANNER_TEST")
	REFERENCES "SCANNER_TEST" ("CODE_SCANNER_TEST") ;


--  Table IRM_TEST


CREATE TABLE "IRM_TEST" 
(	"CODE_IRM_TEST" NUMBER(11,0), 
	"REMAQUES_IRM_TEST" VARCHAR2(512), 
	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"DATE_IRM_TEST" DATE
	) ;
ALTER TABLE "IRM_TEST" ADD CONSTRAINT "IRM_TEST_PK" PRIMARY KEY ("CODE_IRM_TEST");
ALTER TABLE "IRM_TEST" MODIFY ("CODE_IRM_TEST" NOT NULL );
ALTER TABLE "IRM_TEST" ADD CONSTRAINT "IRM_TEST_DIAGNOSTIC_FK1" FOREIGN KEY ("CODE_DIAGNOSTIC")
	REFERENCES "DIAGNOSTIC" ("CODE_DIAGNOSTIC") ;


--  Table LABORATOIRE


CREATE TABLE "LABORATOIRE" 
(	"CODE_LABORATOIRE" NUMBER(11,0), 
	"NOM_LABORATOIRE" VARCHAR2(255)
	);
ALTER TABLE "LABORATOIRE" ADD CONSTRAINT "LABORATOIRE_PK" PRIMARY KEY ("CODE_LABORATOIRE");
ALTER TABLE "LABORATOIRE" MODIFY ("CODE_LABORATOIRE" NOT NULL );


--  Table MEDICAMENT


CREATE TABLE "MEDICAMENT" 
(	"CODE_MEDICAMENT" NUMBER(11,0), 
	"NOM_MEDICAMENT" VARCHAR2(255), 
	"PRIX_MEDICAMENT" NUMBER(11,0), 
	"DATE_EXPR_MEDICAMENT" DATE, 
	"DESCRIPTION_MEDICAMAENT" CLOB, 
	"CODE_LABORATOIRE" NUMBER(11,0)
	);
ALTER TABLE "MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_PK" PRIMARY KEY ("CODE_MEDICAMENT");
ALTER TABLE "MEDICAMENT" MODIFY ("CODE_MEDICAMENT" NOT NULL );
ALTER TABLE "MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_LABORATOIRE_FK1" FOREIGN KEY ("CODE_LABORATOIRE")
	REFERENCES "LABORATOIRE" ("CODE_LABORATOIRE") ;


--  Table ORDONNANCE


CREATE TABLE "ORDONNANCE" 
(	"CODE_ORDONNANCE" NUMBER(11,0), 
	"JOURS_REPOS_ORDONNANCE" NUMBER(11,0)
	);
ALTER TABLE "ORDONNANCE" ADD CONSTRAINT "ORDONNANCE_PK" PRIMARY KEY ("CODE_ORDONNANCE");
ALTER TABLE "ORDONNANCE" MODIFY ("CODE_ORDONNANCE" NOT NULL );


--  Table PATIENT


CREATE TABLE "PATIENT" 
(	"CODE_PATIENT" NUMBER(11,0), 
	"NOM_PATIENT" VARCHAR2(250), 
	"PRENOM_PATIENT" VARCHAR2(250), 
	"NUMERO_TEL_PATIENT" VARCHAR2(250), 
	"DATE_NAISSANCE_PATIENT" DATE, 
	"CODE_SEXE" NUMBER(11,0), 
	"CODE_COMPAGNIE_ASSURENCE" NUMBER(11,0), 
	"STATUT_SOCIAL" VARCHAR2(250), 
	"ADRESSE_PATIENT" VARCHAR2(250)
	);
ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("CODE_PATIENT");
ALTER TABLE "PATIENT" MODIFY ("CODE_PATIENT" NOT NULL );
ALTER TABLE "PATIENT" MODIFY ("NOM_PATIENT" NOT NULL );
ALTER TABLE "PATIENT" MODIFY ("PRENOM_PATIENT" NOT NULL );
ALTER TABLE "PATIENT" MODIFY ("DATE_NAISSANCE_PATIENT" NOT NULL );
ALTER TABLE "PATIENT" MODIFY ("CODE_SEXE" NOT NULL );
ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_COMPAGNIE_ASSUREN_FK1" FOREIGN KEY ("CODE_COMPAGNIE_ASSURENCE")
	REFERENCES "COMPAGNIE_ASSURENCE" ("CODE_COMPAGNIE_ASSURENCE") ;
ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_SEXE_FK1" FOREIGN KEY ("CODE_SEXE")
	REFERENCES "SEXE" ("CODE_SEXE") ;


--  Table RADIOGRAPHIE_TEST


CREATE TABLE "RADIOGRAPHIE_TEST" 
(	"CODE_RADIOGRAPHIE_TEST" NUMBER(11,0), 
	"REMAQUES_RADIORAPHIE_TEST" VARCHAR2(512), 
	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"DATA_RADIOGRAPHIE_TEST" DATE
	);
ALTER TABLE "RADIOGRAPHIE_TEST" ADD CONSTRAINT "RADIOGRAPHIE_TEST_PK" PRIMARY KEY ("CODE_RADIOGRAPHIE_TEST");
ALTER TABLE "RADIOGRAPHIE_TEST" MODIFY ("CODE_RADIOGRAPHIE_TEST" NOT NULL );
ALTER TABLE "RADIOGRAPHIE_TEST" ADD CONSTRAINT "RADIOGRAPHIE_TEST_DIAGNOS_FK1" FOREIGN KEY ("CODE_DIAGNOSTIC")
	REFERENCES "DIAGNOSTIC" ("CODE_DIAGNOSTIC") ;


--  Table SCANNER_TEST


CREATE TABLE "SCANNER_TEST" 
(	"CODE_SCANNER_TEST" NUMBER(11,0), 
	"REMAQUES_SCANNER_TEST" VARCHAR2(512), 
	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"DATE_SCANNER_TEST" DATE
	);
ALTER TABLE "SCANNER_TEST" ADD CONSTRAINT "SCANNER_TEST_PK" PRIMARY KEY ("CODE_SCANNER_TEST");
ALTER TABLE "SCANNER_TEST" MODIFY ("CODE_SCANNER_TEST" NOT NULL );
ALTER TABLE "SCANNER_TEST" ADD CONSTRAINT "SCANNER_TEST_DIAGNOSTIC_FK1" FOREIGN KEY ("CODE_DIAGNOSTIC")
	REFERENCES "DIAGNOSTIC" ("CODE_DIAGNOSTIC") ;


--  Table SEXE


CREATE TABLE "SEXE" 
(	"CODE_SEXE" NUMBER(11,0), 
	"TYPE_SEXE" VARCHAR2(255)
	);
ALTER TABLE "SEXE" ADD CONSTRAINT "SEXE_PK" PRIMARY KEY ("CODE_SEXE");
ALTER TABLE "SEXE" MODIFY ("CODE_SEXE" NOT NULL );
ALTER TABLE "SEXE" MODIFY ("TYPE_SEXE" NOT NULL );


--  Table VISITE


CREATE TABLE "VISITE" 
(	"CODE_VISITE" NUMBER(11,0), 
	"DATE_VISITE" DATE, 
	"CAUSE_VISITE" VARCHAR2(250), 
	"CODE_PATIENT" NUMBER(11,0), 
	"CODE_DIAGNOSTIC" NUMBER(11,0), 
	"CODE_ORDONNANCE" NUMBER(11,0), 
	"CODE_FACTURE" NUMBER(11,0)
	);
ALTER TABLE "VISITE" MODIFY ("CODE_VISITE" NOT NULL );
ALTER TABLE "VISITE" ADD CONSTRAINT "VISITE_PK" PRIMARY KEY ("CODE_VISITE");
ALTER TABLE "VISITE" ADD CONSTRAINT "VISITE_DIAGNOSTIC_FK1" FOREIGN KEY ("CODE_DIAGNOSTIC")
	REFERENCES "DIAGNOSTIC" ("CODE_DIAGNOSTIC") ;
ALTER TABLE "VISITE" ADD CONSTRAINT "VISITE_FACTURE_FK1" FOREIGN KEY ("CODE_FACTURE")
	REFERENCES "FACTURE" ("CODE_FACTURE") ;
ALTER TABLE "VISITE" ADD CONSTRAINT "VISITE_ORDONNANCE_FK1" FOREIGN KEY ("CODE_ORDONNANCE")
	REFERENCES "ORDONNANCE" ("CODE_ORDONNANCE") ;
ALTER TABLE "VISITE" ADD CONSTRAINT "VISITE_PATIENT_FK1" FOREIGN KEY ("CODE_PATIENT")
	REFERENCES "PATIENT" ("CODE_PATIENT") ;



--  Données Données Données Données Données Données Données Données --



--   INSERTION DES DONNEES POUR LA TABLE SEXE


Insert into SEXE (CODE_SEXE,TYPE_SEXE) values (1,'Male');
Insert into SEXE (CODE_SEXE,TYPE_SEXE) values (2,'Female');
Insert into SEXE (CODE_SEXE,TYPE_SEXE) values (3,'Autre');


--   INSERTION DES DONNEES POUR LA TABLE FACTURE


Insert into FACTURE (CODE_FACTURE,MONTANT_FACTURE,STATUS_FACTURE,METHODE_PAYEMENT) values (1,45,'non paye','espece');


--   INSERTION DES DONNEES POUR LA TABLE COMPAGNIE_ASSURENCE


Insert into COMPAGNIE_ASSURENCE (CODE_COMPAGNIE_ASSURENCE,NOM_COMPAGNIE_ASSURENCE,NUMERO_TEL_COMPAGNIE_ASSURENCE,ADRESSE_COMPAGNIE_ASSURENCE) values (1,'CNSS','7037463','3, rue haj saleh tunis');
Insert into COMPAGNIE_ASSURENCE (CODE_COMPAGNIE_ASSURENCE,NOM_COMPAGNIE_ASSURENCE,NUMERO_TEL_COMPAGNIE_ASSURENCE,ADRESSE_COMPAGNIE_ASSURENCE) values (2,'CNRPS','71362475','4, rue mounir sousse');


--   INSERTION DES DONNEES POUR LA TABLE IMAGE_IRM


Insert into IMAGE_IRM (CODE_IMAGE_IRM,DESC_IMAGE_IRM,FILE_IMAGE_IRM,CODE_IRM_TEST) values (1,'rien de special','c:/irm/img1.jpg',1);
Insert into IMAGE_IRM (CODE_IMAGE_IRM,DESC_IMAGE_IRM,FILE_IMAGE_IRM,CODE_IRM_TEST) values (2,'rien de special','c:/irm/img2.jpg',1);


--   INSERTION DES DONNEES POUR LA TABLE IRM_TEST


Insert into IRM_TEST (CODE_IRM_TEST,REMAQUES_IRM_TEST,CODE_DIAGNOSTIC,DATE_IRM_TEST) values (1,'rien de special',1,to_date('02/03/2015','dd/mm/yyyy'));


--   INSERTION DES DONNEES POUR LA TABLE CONTIENT


Insert into CONTIENT (CODE_ORDONNANCE,CODE_MEDICAMENT,QUANTITE_CONTIENT) values (1,1,2);
Insert into CONTIENT (CODE_ORDONNANCE,CODE_MEDICAMENT,QUANTITE_CONTIENT) values (1,2,1);


--   INSERTION DES DONNEES POUR LA TABLE EXAMEN_URINE


Insert into EXAMEN_URINE (CODE_EXAMEN_URINE,GLUCOSE_EXAMEN_URINE,BILIRUBINE_EXAMEN_URINE,CETONIQUE_EXAMEN_URINE,DENSITE_EXAMEN_URINE,PH_EXAMEN_URINE,PROTEINES_EXAMEN_URINE,UROBILINOGENES_EXAMEN_URINE,NITRITES,LEUCOYTES_EXAMEN_URINE,DATE_EXAMEN_URINE,REMARQUES_EXAMEN_URINE) values (1,43,223,432,12,23,1,44,23,43,to_date('02/03/2015','dd/mm/yyyy'),'ph tres eleve');


--   INSERTION DES DONNEES POUR LA TABLE LABORATOIRE


Insert into LABORATOIRE (CODE_LABORATOIRE,NOM_LABORATOIRE) values (1,'labo1');
Insert into LABORATOIRE (CODE_LABORATOIRE,NOM_LABORATOIRE) values (2,'labo2');


--   INSERTION DES DONNEES POUR LA TABLE VISITE


Insert into VISITE (CODE_VISITE,DATE_VISITE,CAUSE_VISITE,CODE_PATIENT,CODE_DIAGNOSTIC,CODE_ORDONNANCE,CODE_FACTURE) values (1,to_date('08/03/2015','dd/mm/yyyy'),'fievre, fatigue',1,1,1,1);


--   INSERTION DES DONNEES POUR LA TABLE ORDONNANCE


Insert into ORDONNANCE (CODE_ORDONNANCE,JOURS_REPOS_ORDONNANCE) values (1,3);


--   INSERTION DES DONNEES POUR LA TABLE ECHOGRAPHIE_TEST


Insert into ECHOGRAPHIE_TEST (CODE_ECHOGRAPHIE_TEST,REMAQUES_ECHOGRAPHIE_TEST,CODE_DIAGNOSTIC,DATE_ECOGRAPHIE_TEST) values (1,'presence de VIH au niveau des jambes',1,to_date('05/03/2015','dd/mm/yyyy'));


--   INSERTION DES DONNEES POUR LA TABLE MEDICAMENT


Insert into MEDICAMENT (CODE_MEDICAMENT,NOM_MEDICAMENT,PRIX_MEDICAMENT,DATE_EXPR_MEDICAMENT,DESCRIPTION_MEDICAMAENT,CODE_LABORATOIRE) values (1,'aspegic',3,to_date('08/03/2020','dd/mm/yyyy'),'un tres bon medicament',1);
Insert into MEDICAMENT (CODE_MEDICAMENT,NOM_MEDICAMENT,PRIX_MEDICAMENT,DATE_EXPR_MEDICAMENT,DESCRIPTION_MEDICAMAENT,CODE_LABORATOIRE) values (2,'fervex',4,to_date('05/03/2034','dd/mm/yyyy'),'pas mal aussi',2);


--   INSERTION DES DONNEES POUR LA TABLE PATIENT


Insert into PATIENT (CODE_PATIENT,NOM_PATIENT,PRENOM_PATIENT,NUMERO_TEL_PATIENT,DATE_NAISSANCE_PATIENT,CODE_SEXE,CODE_COMPAGNIE_ASSURENCE,STATUT_SOCIAL,ADRESSE_PATIENT) values (1,'khabthani','abdelaziz','25650647',to_date('05/03/1991','dd/mm/yyyy'),1,1,'celibataire','01, rue elbouhtouri ariana 2080');


--   INSERTION DES DONNEES POUR LA TABLE DIAGNOSTIC


Insert into DIAGNOSTIC (CODE_DIAGNOSTIC,TEMPERATURE_DIAGNOSTIC,TENSION_ATERIELLE_DIAGNOSTIC,POIDS_DIAGNOSTIC,MESURE_DIAGNOSTIC,RYTHME_CARDIAQUE_DIAGNOSTIC,AUTR_REMARQUE_DIAGNOSTIC,SYSTEM_RESPIRATOIR_DIAGNOSTIC,ABDOMEN_DIAGNOSTIC,MEMBRES_SUP_DIAGNOSTIC,MEMBRES_INF_DIAGNOSTIC,ORGAN_GENITAUX_DIAGNOSTIC,PEAU_DIAGNOSTIC,TETE_COU_DIAGNOSTIC,CODE_EXAMEN_SANG,CODE_EXAMEN_URINE) values (1,40,11,70,170,'23','yeux rouges','bruit lors du respiration','gonflet','probléme aux articulations','probleme de mouvement','rien de special','jaune','maux au tete',1,1);


--   INSERTION DES DONNEES POUR LA TABLE IMAGE_ECHOGRAPHIE


Insert into IMAGE_ECHOGRAPHIE (CODE_IMAGE_ECHOGRAPHIE,DESC_IMAGE_ECHOGRAPHIE,FILE_IMAGE_ECHOGRAPHIE,CODE_ECHOGRAPHIE_TEST) values (1,'rrien de special','c:/echo/img1.jpg',1);
Insert into IMAGE_ECHOGRAPHIE (CODE_IMAGE_ECHOGRAPHIE,DESC_IMAGE_ECHOGRAPHIE,FILE_IMAGE_ECHOGRAPHIE,CODE_ECHOGRAPHIE_TEST) values (2,'rien de special','c:/echo/img2.jpg',1);


--   INSERTION DES DONNEES POUR LA TABLE EXAMEN_SANG


Insert into EXAMEN_SANG (CODE_EXAMEN_SANG,HEMATIES_EXAMEN_SANG,HEMATOCRITE_EXAMEN_SANG,VGM_EXAMEN_SANG,TCMH_EXAMEN_SANG,CCMH_EXAMEN_SANG,LEUCOYTES_EXAMEN_SANG,NEUTROPHILES_EXAMEN_SANG,EOSINOPHILES_EXAMEN_SANG,BASOPHILES_EXAMEN_SANG,LYMPHOCYTES_EXAMEN_SANG,MONOCYTES_EXAMEN_SANG,NUM_PLAQUETTE_EXAMEN_SANG,VITESSE_SEDIM_EXAMEN_SANG,DATE_EXAMEN_SANG,REMARQUES_EXAMEN_SANG) values (1,2,1,3,2,4,5,12,243,234,122,3,1,342,to_date('08/03/2015','dd/mm/yyyy'),'manque du glucose');



--  Requétes Requétes Requétes Requétes Requétes Requétes Requétes Requétes --



--   Toutes les visites de Mr Abdelaziz Khabthani


SELECT PATIENT.NOM_PATIENT, PATIENT.PRENOM_PATIENT, VISITE.CAUSE_VISITE, VISITE.DATE_VISITE
FROM PATIENT
INNER JOIN VISITE
    ON PATIENT.CODE_PATIENT = VISITE.CODE_PATIENT
WHERE PATIENT.NOM_PATIENT ='khabthani'
    AND PATIENT.PRENOM_PATIENT = 'abdelaziz';


--   Les Factures non payés de Abdelaziz Khabthani


SELECT PATIENT.NOM_PATIENT, PATIENT.PRENOM_PATIENT, VISITE.DATE_VISITE , FACTURE.MONTANT_FACTURE
FROM PATIENT
INNER JOIN VISITE
    ON PATIENT.CODE_PATIENT = VISITE.CODE_PATIENT
INNER JOIN FACTURE
    ON VISITE.CODE_FACTURE = FACTURE.CODE_FACTURE
WHERE PATIENT.NOM_PATIENT ='khabthani'
    AND PATIENT.PRENOM_PATIENT = 'abdelaziz'
    AND FACTURE.STATUS_FACTURE = 'non paye';


--   Les patiens assuré par CNSS 


SELECT PATIENT.NOM_PATIENT, PATIENT.PRENOM_PATIENT, PATIENT.ADRESSE_PATIENT, PATIENT.NUMERO_TEL_PATIENT
FROM PATIENT
INNER JOIN COMPAGNIE_ASSURENCE
    ON PATIENT.CODE_COMPAGNIE_ASSURENCE = COMPAGNIE_ASSURENCE.CODE_COMPAGNIE_ASSURENCE
WHERE COMPAGNIE_ASSURENCE.NOM_COMPAGNIE_ASSURENCE = 'CNSS';


--   Listes des medicaments donné à Abdelaziz Khabthani le 08/03/2015


SELECT MEDICAMENT.NOM_MEDICAMENT, LABORATOIRE.NOM_LABORATOIRE, CONTIENT.QUANTITE_CONTIENT
FROM PATIENT
INNER JOIN VISITE
    ON PATIENT.CODE_PATIENT = VISITE.CODE_PATIENT
INNER JOIN ORDONNANCE
    ON VISITE.CODE_ORDONNANCE = ORDONNANCE.CODE_ORDONNANCE
INNER JOIN CONTIENT
    ON ORDONNANCE.CODE_ORDONNANCE = CONTIENT.CODE_ORDONNANCE
INNER JOIN MEDICAMENT
    ON CONTIENT.CODE_MEDICAMENT = MEDICAMENT.CODE_MEDICAMENT
INNER JOIN LABORATOIRE
    ON MEDICAMENT.CODE_LABORATOIRE = LABORATOIRE.CODE_LABORATOIRE
WHERE PATIENT.NOM_PATIENT = 'khabthani'
    AND PATIENT.PRENOM_PATIENT = 'abdelaziz' AND VISITE.DATE_VISITE = to_date('08/03/2015','dd/mm/yyyy');